/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCreateIndexRouteImport } from './routes/app/create/index'
import { Route as AppLearningPlansLearningPlanIdIndexRouteImport } from './routes/app/learning-plans/$learningPlanId/index'
import { Route as AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRouteImport } from './routes/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreateIndexRoute = AppCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLearningPlansLearningPlanIdIndexRoute =
  AppLearningPlansLearningPlanIdIndexRouteImport.update({
    id: '/learning-plans/$learningPlanId/',
    path: '/learning-plans/$learningPlanId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRoute =
  AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRouteImport.update({
    id: '/learning-plans/$learningPlanId/learning-tasks/$learningTaskId',
    path: '/learning-plans/$learningPlanId/learning-tasks/$learningTaskId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/app/create': typeof AppCreateIndexRoute
  '/app/learning-plans/$learningPlanId': typeof AppLearningPlansLearningPlanIdIndexRoute
  '/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId': typeof AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/app/create': typeof AppCreateIndexRoute
  '/app/learning-plans/$learningPlanId': typeof AppLearningPlansLearningPlanIdIndexRoute
  '/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId': typeof AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/app/create/': typeof AppCreateIndexRoute
  '/app/learning-plans/$learningPlanId/': typeof AppLearningPlansLearningPlanIdIndexRoute
  '/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId': typeof AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/'
    | '/login'
    | '/signup'
    | '/app/create'
    | '/app/learning-plans/$learningPlanId'
    | '/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/create'
    | '/app/learning-plans/$learningPlanId'
    | '/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/'
    | '/login/'
    | '/signup/'
    | '/app/create/'
    | '/app/learning-plans/$learningPlanId/'
    | '/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/create/': {
      id: '/app/create/'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/learning-plans/$learningPlanId/': {
      id: '/app/learning-plans/$learningPlanId/'
      path: '/learning-plans/$learningPlanId'
      fullPath: '/app/learning-plans/$learningPlanId'
      preLoaderRoute: typeof AppLearningPlansLearningPlanIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId': {
      id: '/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId'
      path: '/learning-plans/$learningPlanId/learning-tasks/$learningTaskId'
      fullPath: '/app/learning-plans/$learningPlanId/learning-tasks/$learningTaskId'
      preLoaderRoute: typeof AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCreateIndexRoute: typeof AppCreateIndexRoute
  AppLearningPlansLearningPlanIdIndexRoute: typeof AppLearningPlansLearningPlanIdIndexRoute
  AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRoute: typeof AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCreateIndexRoute: AppCreateIndexRoute,
  AppLearningPlansLearningPlanIdIndexRoute:
    AppLearningPlansLearningPlanIdIndexRoute,
  AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRoute:
    AppLearningPlansLearningPlanIdLearningTasksLearningTaskIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
