/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Google OAuth 시작
     * @description Google 로그인 페이지로 리다이렉트합니다.
     *
     *     **옵션**: `redirectPath`로 로그인 후 이동할 경로 지정
     */
    get: {
      parameters: {
        query?: {
          redirectPath?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Google OAuth consent page로 리다이렉트합니다. */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/google/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Google OAuth 콜백
     * @description Google OAuth 인증 완료 후 콜백 처리를 담당합니다. 세션 쿠키를 발급합니다.
     */
    get: {
      parameters: {
        query: {
          code: string;
          state: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 세션 쿠키를 설정한 뒤 redirectPath로 리다이렉트합니다. */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/magic-link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 이메일 매직링크 요청
     * @description 입력한 이메일로 로그인 링크를 전송합니다. 비밀번호 없이 로그인할 수 있습니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            redirectPath: string;
          };
        };
      };
      responses: {
        /** @description 매직링크 전송 요청이 접수되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/magic-link/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 매직링크 검증
     * @description 이메일의 매직링크 토큰을 검증하고 세션을 생성합니다.
     */
    get: {
      parameters: {
        query: {
          token: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 세션 쿠키를 설정한 뒤 redirectPath로 리다이렉트합니다. */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 현재 사용자 조회
     * @description 현재 로그인한 사용자의 정보를 조회합니다. 인증 상태 확인에 사용됩니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 현재 로그인한 사용자를 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                displayName: string;
                /** Format: uri */
                avatarUrl: string | null;
                locale: string;
                timezone: string;
                /** @enum {string} */
                subscriptionPlan: "FREE" | "PRO";
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description 현재 세션을 종료하고 쿠키를 삭제합니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 로그아웃되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/materials": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 자료 목록 조회
     * @description 사용자의 학습 자료 목록을 페이지네이션과 함께 조회합니다.
     *
     *     **필터링 옵션**: `status`, `search`, `sort`
     */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          status?: "PENDING" | "PROCESSING" | "READY" | "FAILED";
          search?: string;
          sort?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 자료 목록을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: Array<{
                /** Format: uuid */
                id: string;
                title: string;
                /** @enum {string} */
                sourceType: "FILE" | "TEXT";
                mimeType: string | null;
                fileSize: number | null;
                /** @enum {string} */
                processingStatus: "PENDING" | "PROCESSING" | "READY" | "FAILED";
                summary: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              }>;
              meta: {
                total: number;
                page: number;
                limit: number;
                totalPages: number;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/materials/{materialId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 자료 상세 조회
     * @description 학습 자료의 상세 정보를 조회합니다. 추출된 개념, 원본 텍스트 등을 포함합니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          materialId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 자료 상세를 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                title: string;
                /** @enum {string} */
                sourceType: "FILE" | "TEXT";
                originalFilename: string | null;
                mimeType: string | null;
                fileSize: number | null;
                /** @enum {string} */
                processingStatus: "PENDING" | "PROCESSING" | "READY" | "FAILED";
                /** Format: date-time */
                processedAt: string | null;
                summary: string | null;
                chunkCount: number | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * 자료 삭제
     * @description 학습 자료를 삭제합니다. 연관된 개념, 임베딩도 함께 삭제됩니다.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          materialId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description soft/hard delete 결과를 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              data: {
                /** @enum {string} */
                type: "soft" | "hard";
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * 자료 제목 수정
     * @description 학습 자료의 제목을 수정합니다.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          materialId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            title: string;
          };
        };
      };
      responses: {
        /** @description 자료 제목이 수정되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                title: string;
                /** Format: date-time */
                updatedAt: string;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/materials/uploads/init": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * R2 업로드 세션 생성
     * @description 파일 업로드를 위한 Presigned URL을 발급합니다.
     *
     *     **지원 형식**: PDF, DOCX, TXT 등
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            originalFilename: string;
            mimeType: string;
            fileSize: number;
          };
        };
      };
      responses: {
        /** @description R2 presigned PUT URL을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                uploadId: string;
                objectKey: string;
                /** Format: uri */
                uploadUrl: string;
                /** @enum {string} */
                method: "PUT";
                headers: {
                  [key: string]: string;
                };
                /** Format: date-time */
                expiresAt: string;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/materials/uploads/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * R2 업로드 완료 처리
     * @description R2에 파일 업로드 완료 후 자료 분석을 시작합니다. 비동기 처리 시 `jobId`를 반환합니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** Format: uuid */
            uploadId: string;
            title?: string;
            etag?: string;
          };
        };
      };
      responses: {
        /** @description 동기 처리로 업로드/분석이 완료되었습니다. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                title: string;
                /** @enum {string} */
                processingStatus: "PENDING" | "PROCESSING" | "READY" | "FAILED";
                summary?: string | null;
              };
            };
          };
        };
        /** @description 비동기 처리로 접수되었습니다. */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                jobId: string;
                /** @enum {string} */
                processingStatus: "PENDING" | "PROCESSING" | "READY" | "FAILED";
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/materials/uploads/complete/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * R2 업로드 완료 처리 (SSE 스트림)
     * @description SSE를 통해 업로드 완료 처리 진행 상황을 실시간으로 전달합니다.\n\n**이벤트 타입**:\n- `progress`: 진행 상황 업데이트\n- `complete`: 처리 완료\n- `error`: 에러 발생
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** Format: uuid */
            uploadId: string;
            title?: string;
            etag?: string;
          };
        };
      };
      responses: {
        /** @description SSE 스트림으로 진행 상황을 전달합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": unknown;
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{jobId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 비동기 작업 상태 조회
     * @description 자료 분석 등 비동기 작업의 진행 상태를 확인합니다.
     *
     *     **상태**: `pending`, `processing`, `completed`, `failed`
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          jobId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 작업 상태를 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                jobId: string;
                /** @enum {string} */
                status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
                progress: number | null;
                currentStep: string | null;
                result: {
                  /** Format: uuid */
                  materialId: string;
                  summary: string | null;
                } | null;
                error: {
                  code: string;
                  message: string;
                } | null;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Plan 목록 조회
     * @description 사용자의 학습 계획 목록을 조회합니다.
     *
     *     **필터링**: `status`별 조회 가능
     */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          status?: "ACTIVE" | "PAUSED" | "ARCHIVED" | "COMPLETED";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plan 목록을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: Array<{
                id: string;
                title: string;
                icon: string;
                color: string;
                /** @enum {string} */
                status: "ACTIVE" | "PAUSED" | "ARCHIVED" | "COMPLETED";
                /** @enum {string} */
                goalType: "JOB" | "CERT" | "WORK" | "HOBBY" | "OTHER";
                /** @enum {string} */
                currentLevel: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                progress: {
                  completedSessions: number;
                  totalSessions: number;
                };
                sourceMaterialIds: Array<string>;
              }>;
              meta: {
                total: number;
                page: number;
                limit: number;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Plan 생성
     * @description AI가 자료를 분석하여 학습 계획을 생성합니다. 세션이 자동 생성됩니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            materialIds: Array<string>;
            /** @enum {string} */
            goalType: "JOB" | "CERT" | "WORK" | "HOBBY" | "OTHER";
            /** @enum {string} */
            currentLevel: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
            /** Format: date */
            targetDueDate: string;
            specialRequirements?: string;
            icon?: string;
            color?: string;
          };
        };
      };
      responses: {
        /** @description Plan이 생성되었습니다. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                title: string;
                icon: string;
                color: string;
                /** @enum {string} */
                status: "ACTIVE" | "PAUSED" | "ARCHIVED" | "COMPLETED";
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plans/{planId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Plan 상세 조회
     * @description 학습 계획의 상세 정보를 조회합니다. 세션 목록과 진행률을 포함합니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plan 상세를 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                title: string;
                icon: string;
                color: string;
                /** @enum {string} */
                status: "ACTIVE" | "PAUSED" | "ARCHIVED" | "COMPLETED";
                /** @enum {string} */
                goalType: "JOB" | "CERT" | "WORK" | "HOBBY" | "OTHER";
                /** @enum {string} */
                currentLevel: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
                /** Format: date */
                targetDueDate: string;
                specialRequirements: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                progress: {
                  completedSessions: number;
                  totalSessions: number;
                };
                sourceMaterialIds: Array<string>;
                modules: Array<{
                  /** Format: uuid */
                  id: string;
                  title: string;
                  description: string | null;
                  orderIndex: number;
                }>;
                sessions: Array<{
                  id: string;
                  /** Format: uuid */
                  moduleId: string | null;
                  /** @enum {string} */
                  sessionType: "LEARN";
                  title: string;
                  objective: string | null;
                  orderIndex: number;
                  /** Format: date */
                  scheduledForDate: string;
                  estimatedMinutes: number;
                  /** @enum {string} */
                  status:
                    | "SCHEDULED"
                    | "IN_PROGRESS"
                    | "COMPLETED"
                    | "SKIPPED"
                    | "CANCELED";
                  /** Format: date-time */
                  completedAt: string | null;
                }>;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Plan 삭제
     * @description 학습 계획을 삭제합니다. 세션 기록도 함께 삭제됩니다.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plan이 삭제되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Plan 수정
     * @description 학습 계획의 제목, 아이콘, 색상 등을 수정합니다.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            title?: string;
            icon?: string;
            color?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "PAUSED" | "ARCHIVED" | "COMPLETED";
          };
        };
      };
      responses: {
        /** @description Plan이 수정되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                title: string;
                icon: string;
                color: string;
                /** @enum {string} */
                status: "ACTIVE" | "PAUSED" | "ARCHIVED" | "COMPLETED";
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/plans/{planId}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Plan 상태 변경
     * @description 학습 계획의 상태를 변경합니다.
     *
     *     **상태**: `draft`, `active`, `paused`, `completed`
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            status: "ACTIVE" | "PAUSED" | "ARCHIVED" | "COMPLETED";
          };
        };
      };
      responses: {
        /** @description Plan 상태가 변경되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                status: "ACTIVE" | "PAUSED" | "ARCHIVED" | "COMPLETED";
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/plans/{planId}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Plan Active 설정
     * @description 학습 계획을 활성화합니다. 기존 활성 계획은 자동으로 비활성화됩니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plan이 ACTIVE로 설정되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                status: "ACTIVE" | "PAUSED" | "ARCHIVED" | "COMPLETED";
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/home/queue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 오늘 할 일 큐 조회
     * @description 오늘 학습해야 할 세션 목록을 조회합니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 오늘 예정된 세션을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: Array<{
                /** @enum {string} */
                kind: "SESSION";
                sessionId: string;
                planId: string;
                planTitle: string;
                planIcon: string;
                planColor: string;
                moduleTitle: string;
                sessionTitle: string;
                /** @enum {string} */
                sessionType: "LEARN";
                estimatedMinutes: number;
                /** @enum {string} */
                status:
                  | "SCHEDULED"
                  | "IN_PROGRESS"
                  | "COMPLETED"
                  | "SKIPPED"
                  | "CANCELED";
              }>;
              summary: {
                total: number;
                completed: number;
                estimatedMinutes: number;
                coachingMessage: string;
                streakDays: number;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/{sessionId}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Session Run 생성/재개
     * @description 학습 세션을 시작하거나 중단된 세션을 재개합니다.
     *
     *     **멱등성**: `Idempotency-Key` 헤더로 중복 요청 방지
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          "Idempotency-Key"?: string;
        };
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 복구된 Run을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                runId: string;
                sessionId: string;
                /** @enum {string} */
                status: "RUNNING" | "COMPLETED" | "ABANDONED";
                isRecovery: boolean;
                currentStep: number;
              };
            };
          };
        };
        /** @description 새 Run이 생성되었습니다. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                runId: string;
                sessionId: string;
                /** @enum {string} */
                status: "RUNNING" | "COMPLETED" | "ABANDONED";
                isRecovery: boolean;
                currentStep: number;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/{sessionId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Plan Session 업데이트
     * @description 세션 상태(SKIPPED/CANCELED 등) 또는 예정 날짜를 변경합니다.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            status?:
              | "SCHEDULED"
              | "IN_PROGRESS"
              | "COMPLETED"
              | "SKIPPED"
              | "CANCELED";
            /** Format: date */
            scheduledForDate?: string;
          };
        };
      };
      responses: {
        /** @description 세션이 업데이트되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                sessionId: string;
                /** @enum {string} */
                status:
                  | "SCHEDULED"
                  | "IN_PROGRESS"
                  | "COMPLETED"
                  | "SKIPPED"
                  | "CANCELED";
                /** Format: date */
                scheduledForDate: string;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/session-runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Session Run 목록 조회
     * @description 최근 실행된 세션 런 목록을 조회합니다.
     */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          status?: "RUNNING" | "COMPLETED" | "ABANDONED";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Session Run 목록을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: Array<{
                runId: string;
                /** @enum {string} */
                status: "RUNNING" | "COMPLETED" | "ABANDONED";
                /** Format: date-time */
                startedAt: string;
                /** Format: date-time */
                endedAt: string | null;
                /** @enum {string|null} */
                exitReason:
                  | "USER_EXIT"
                  | "NETWORK"
                  | "ERROR"
                  | "TIMEOUT"
                  | null;
                durationMinutes: number;
                sessionId: string;
                sessionTitle: string;
                /** @enum {string} */
                sessionType: "LEARN";
                planId: string;
                planTitle: string;
                planIcon: string;
                planColor: string;
                summary: {
                  /** Format: uuid */
                  id: string;
                  /** Format: date-time */
                  createdAt: string;
                } | null;
              }>;
              meta: {
                total: number;
                page: number;
                limit: number;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session-runs/{runId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Session Run 상세 조회
     * @description 세션 런과 블루프린트(스텝), 진행 상태를 조회합니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Session Run 상세를 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                runId: string;
                /** @enum {string} */
                status: "RUNNING" | "COMPLETED" | "ABANDONED";
                /** Format: date-time */
                startedAt: string;
                /** Format: date-time */
                endedAt: string | null;
                /** @enum {string|null} */
                exitReason:
                  | "USER_EXIT"
                  | "NETWORK"
                  | "ERROR"
                  | "TIMEOUT"
                  | null;
                session: {
                  sessionId: string;
                  title: string;
                  objective: string | null;
                  /** @enum {string} */
                  sessionType: "LEARN";
                  estimatedMinutes: number;
                  module: {
                    /** Format: uuid */
                    id: string;
                    title: string;
                  } | null;
                  plan: {
                    id: string;
                    title: string;
                    icon: string;
                    color: string;
                  };
                };
                blueprint: {
                  schemaVersion: number;
                  /** Format: uuid */
                  blueprintId: string;
                  /** Format: date-time */
                  createdAt: string;
                  steps: Array<| {
                        id: string;
                        estimatedSeconds?: number;
                        /** @enum {string} */
                        intent?:
                          | "INTRO"
                          | "EXPLAIN"
                          | "RETRIEVAL"
                          | "PRACTICE"
                          | "WRAPUP";
                        /** @enum {string} */
                        type: "SESSION_INTRO";
                        planTitle: string;
                        moduleTitle: string;
                        sessionTitle: string;
                        durationMinutes: number;
                        /** @enum {string} */
                        difficulty: "beginner" | "intermediate" | "advanced";
                        learningGoals: Array<string>;
                        questionsToCover: Array<string>;
                        /** @default [] */
                        prerequisites: Array<string>;
                      }
                    | {
                        id: string;
                        estimatedSeconds?: number;
                        /** @enum {string} */
                        intent?:
                          | "INTRO"
                          | "EXPLAIN"
                          | "RETRIEVAL"
                          | "PRACTICE"
                          | "WRAPUP";
                        /** @enum {string} */
                        type: "CHECK";
                        question: string;
                        options: Array<string>;
                        answerIndex: number;
                        explanation?: string;
                      }
                    | {
                        id: string;
                        estimatedSeconds?: number;
                        /** @enum {string} */
                        intent?:
                          | "INTRO"
                          | "EXPLAIN"
                          | "RETRIEVAL"
                          | "PRACTICE"
                          | "WRAPUP";
                        /** @enum {string} */
                        type: "CLOZE";
                        sentence: string;
                        blankId: string;
                        options: Array<string>;
                        answerIndex: number;
                        explanation?: string;
                      }
                    | {
                        id: string;
                        estimatedSeconds?: number;
                        /** @enum {string} */
                        intent?:
                          | "INTRO"
                          | "EXPLAIN"
                          | "RETRIEVAL"
                          | "PRACTICE"
                          | "WRAPUP";
                        /** @enum {string} */
                        type: "MATCHING";
                        instruction: string;
                        pairs: Array<{
                          id: string;
                          left: string;
                          right: string;
                        }>;
                      }
                    | {
                        id: string;
                        estimatedSeconds?: number;
                        /** @enum {string} */
                        intent?:
                          | "INTRO"
                          | "EXPLAIN"
                          | "RETRIEVAL"
                          | "PRACTICE"
                          | "WRAPUP";
                        /** @enum {string} */
                        type: "FLASHCARD";
                        front: string;
                        back: string;
                      }
                    | {
                        id: string;
                        estimatedSeconds?: number;
                        /** @enum {string} */
                        intent?:
                          | "INTRO"
                          | "EXPLAIN"
                          | "RETRIEVAL"
                          | "PRACTICE"
                          | "WRAPUP";
                        /** @enum {string} */
                        type: "SPEED_OX";
                        statement: string;
                        isTrue: boolean;
                        explanation?: string;
                      }
                    | {
                        id: string;
                        estimatedSeconds?: number;
                        /** @enum {string} */
                        intent?:
                          | "INTRO"
                          | "EXPLAIN"
                          | "RETRIEVAL"
                          | "PRACTICE"
                          | "WRAPUP";
                        /** @enum {string} */
                        type: "APPLICATION";
                        scenario: string;
                        question: string;
                        options: Array<string>;
                        correctIndex: number;
                        feedback?: string;
                      }
                    | {
                        id: string;
                        estimatedSeconds?: number;
                        /** @enum {string} */
                        intent?:
                          | "INTRO"
                          | "EXPLAIN"
                          | "RETRIEVAL"
                          | "PRACTICE"
                          | "WRAPUP";
                        /** @enum {string} */
                        type: "SESSION_SUMMARY";
                        /** @default 🎉 */
                        celebrationEmoji: string;
                        encouragement: string;
                        studyTimeMinutes?: number;
                        /** @default [] */
                        completedActivities: Array<string>;
                        keyTakeaways: Array<string>;
                        nextSessionPreview?: {
                          title: string;
                          description?: string;
                        };
                      }>;
                  /** @default 0 */
                  startStepIndex: number;
                };
                progress: {
                  stepIndex: number;
                  inputs: {
                    [key: string]: unknown;
                  };
                  /** Format: date-time */
                  savedAt: string | null;
                };
                summary: {
                  /** Format: uuid */
                  id: string;
                  summaryMd: string;
                  /** Format: date-time */
                  createdAt: string;
                } | null;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session-runs/{runId}/checkins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Session Checkins 조회
     * @description 세션 런에 기록된 체크인 로그를 조회합니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 체크인 목록을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: Array<{
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                kind: "QUESTION" | "SELF_ASSESSMENT" | "BEHAVIOR_SIGNAL";
                prompt: string;
                responseJson: {
                  [key: string]: unknown;
                } | null;
                /** Format: date-time */
                recordedAt: string;
              }>;
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Session Checkin 기록
     * @description 세션 런에 체크인을 기록합니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            kind: "QUESTION" | "SELF_ASSESSMENT" | "BEHAVIOR_SIGNAL";
            prompt: string;
            responseJson?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description 체크인이 기록되었습니다. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                recordedAt: string;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session-runs/{runId}/activities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Session Activities 조회
     * @description 세션 런에 기록된 액티비티 로그를 조회합니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 액티비티 목록을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: Array<{
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                kind: "EXERCISE" | "MCQ" | "FREEFORM" | "CODE";
                prompt: string;
                userAnswer: string | null;
                aiEvalJson: {
                  [key: string]: unknown;
                } | null;
                /** Format: date-time */
                createdAt: string;
              }>;
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Session Activity 기록
     * @description 세션 런에 학습 액티비티를 기록합니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            kind: "EXERCISE" | "MCQ" | "FREEFORM" | "CODE";
            prompt: string;
            userAnswer?: string;
            aiEvalJson?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description 액티비티가 기록되었습니다. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                createdAt: string;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session-runs/{runId}/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Session Run 진행 저장
     * @description 학습 진행 상황을 저장합니다. 현재 읽고 있는 개념 위치 등을 기록합니다.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            stepIndex: number;
            inputs: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description 진행이 저장되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                runId: string;
                /** Format: date-time */
                savedAt: string;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/session-runs/{runId}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Session Run 완료
     * @description 학습 세션을 정상적으로 완료 처리합니다. 학습 시간이 기록됩니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Session Run이 완료되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                runId: string;
                /** @enum {string} */
                status: "RUNNING" | "COMPLETED" | "ABANDONED";
                summary: {
                  /** Format: uuid */
                  id: string;
                } | null;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session-runs/{runId}/abandon": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Session Run 중단
     * @description 학습 세션을 중단합니다. 중단 사유를 함께 기록할 수 있습니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            reason: "USER_EXIT" | "NETWORK" | "ERROR" | "TIMEOUT";
          };
        };
      };
      responses: {
        /** @description Session Run이 중단되었습니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                runId: string;
                /** @enum {string} */
                status: "RUNNING" | "COMPLETED" | "ABANDONED";
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/chat/threads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 채팅 스레드 생성
     * @description AI 튜터와 대화할 새 채팅 스레드를 생성합니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            scopeType: "PLAN" | "SESSION";
            scopeId: string;
          };
        };
      };
      responses: {
        /** @description 채팅 스레드가 생성되었습니다. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                threadId: string;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/chat/threads/{threadId}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 스레드 메시지 목록
     * @description 채팅 스레드의 전체 대화 내역을 조회합니다.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          threadId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 메시지 목록을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: Array<{
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                role: "USER" | "ASSISTANT" | "SYSTEM";
                contentMd: string;
                citations?: Array<{
                  /** Format: uuid */
                  chunkId: string;
                  materialTitle: string;
                  quote: string;
                  pageRange?: string;
                }>;
              }>;
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    put?: never;
    /**
     * 메시지 전송
     * @description AI 튜터에게 질문을 보내고 답변을 받습니다. 학습 자료 컨텍스트 기반으로 응답합니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          threadId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            content: string;
          };
        };
      };
      responses: {
        /** @description AI 답변을 반환합니다. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                role: "USER" | "ASSISTANT" | "SYSTEM";
                contentMd: string;
                citations?: Array<{
                  /** Format: uuid */
                  chunkId: string;
                  materialTitle: string;
                  quote: string;
                  pageRange?: string;
                }>;
              };
            };
          };
        };
        /** @description 에러 응답 */
        default: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
                validation?: Array<{
                  field: string;
                  code: string;
                  message: string;
                }>;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        code: string;
        message: string;
        details?: {
          [key: string]: unknown;
        };
        validation?: Array<{
          field: string;
          code: string;
          message: string;
        }>;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
